/*
  # Extend Blog Posts for Content Automation System

  ## Overview
  Adds new fields to blog_posts to support the full content workflow,
  internal linking, image prompts, AI generation tracking, and SEO connections.

  ## Changes to blog_posts

  ### New SEO Connection Fields
  - related_services text[] — links to service pages
  - related_industries text[] — links to industry pages
  - related_locations text[] — links to location pages
  - cluster_id uuid — associates post with a keyword cluster
  - keyword_id uuid — source keyword that triggered this post
  - audience_type text — local_business | ecommerce | both
  - content_type text — pillar | supporting | listicle | how_to | case_study | news
  - cta_type text — audit | strategy_call | contact | resource | none

  ### New Image Prompt Fields
  - featured_image_prompt text — AI image generation prompt for hero image
  - social_image_prompt text — prompt for social share image
  - inline_image_prompts text[] — prompts for body images
  - featured_image_alt text — alt text for featured image
  - social_image_url text — social share image URL

  ### New Content Generation Fields
  - outline jsonb — structured outline generated by AI
  - faq_section jsonb — generated FAQ Q&A pairs
  - cta_block text — generated CTA block HTML/text
  - internal_links jsonb — suggested internal link targets
  - generation_mode text — how this draft was created
  - ai_generated boolean — flag for AI-assisted content

  ### New Workflow Fields
  - workflow_status text — content_idea | outline_ready | draft_ready | review_needed | approved | published
  - workflow_notes text — reviewer notes
*/

DO $$
BEGIN
  -- SEO Connections
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='related_services') THEN
    ALTER TABLE blog_posts ADD COLUMN related_services text[];
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='related_industries') THEN
    ALTER TABLE blog_posts ADD COLUMN related_industries text[];
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='related_locations') THEN
    ALTER TABLE blog_posts ADD COLUMN related_locations text[];
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='cluster_id') THEN
    ALTER TABLE blog_posts ADD COLUMN cluster_id uuid REFERENCES keyword_clusters(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='keyword_id') THEN
    ALTER TABLE blog_posts ADD COLUMN keyword_id uuid REFERENCES keywords(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='audience_type') THEN
    ALTER TABLE blog_posts ADD COLUMN audience_type text DEFAULT 'both';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='content_type') THEN
    ALTER TABLE blog_posts ADD COLUMN content_type text DEFAULT 'supporting';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='cta_type') THEN
    ALTER TABLE blog_posts ADD COLUMN cta_type text DEFAULT 'audit';
  END IF;

  -- Image Prompts
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='featured_image_prompt') THEN
    ALTER TABLE blog_posts ADD COLUMN featured_image_prompt text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='social_image_prompt') THEN
    ALTER TABLE blog_posts ADD COLUMN social_image_prompt text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='inline_image_prompts') THEN
    ALTER TABLE blog_posts ADD COLUMN inline_image_prompts text[];
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='featured_image_alt') THEN
    ALTER TABLE blog_posts ADD COLUMN featured_image_alt text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='social_image_url') THEN
    ALTER TABLE blog_posts ADD COLUMN social_image_url text;
  END IF;

  -- Content Generation
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='outline') THEN
    ALTER TABLE blog_posts ADD COLUMN outline jsonb;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='faq_section') THEN
    ALTER TABLE blog_posts ADD COLUMN faq_section jsonb;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='cta_block') THEN
    ALTER TABLE blog_posts ADD COLUMN cta_block text;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='internal_links') THEN
    ALTER TABLE blog_posts ADD COLUMN internal_links jsonb;
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='generation_mode') THEN
    ALTER TABLE blog_posts ADD COLUMN generation_mode text DEFAULT 'manual';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='ai_generated') THEN
    ALTER TABLE blog_posts ADD COLUMN ai_generated boolean DEFAULT false;
  END IF;

  -- Workflow
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='workflow_status') THEN
    ALTER TABLE blog_posts ADD COLUMN workflow_status text DEFAULT 'content_idea'
      CHECK (workflow_status IN ('content_idea','outline_ready','draft_ready','review_needed','approved','published'));
  END IF;

  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='blog_posts' AND column_name='workflow_notes') THEN
    ALTER TABLE blog_posts ADD COLUMN workflow_notes text;
  END IF;
END $$;
